import { z } from "zod";
import { createGenerateObject } from "@/server/lib/llms";
import { getModel } from "@/server/lib/llms/model";
import {
  canonicalDecisionSchema,
  canonicalRuleSchema,
  type CanonicalRuleCreateInput,
} from "@/server/features/policy-plane/canonical-schema";

const compilerOutputSchema = z
  .object({
    type: z.enum(["guardrail", "automation", "preference"]),
    name: z.string().min(1),
    description: z.string().min(1).optional(),
    priority: z.number().int().min(-1000).max(1000).default(0),
    enabled: z.boolean().default(true),
    decision: canonicalDecisionSchema.optional(),
    resource: z.enum(["email", "calendar", "task", "rule", "preference", "workflow"]),
    operation: z.string().min(1).optional(),
    conditions: z
      .array(
        z
          .object({
            field: z.string().min(1),
            op: z.enum([
              "eq",
              "neq",
              "in",
              "not_in",
              "contains",
              "gt",
              "gte",
              "lt",
              "lte",
              "exists",
            ]),
            valueJson: z.string().max(4_000).optional(),
          })
          .strict(),
      )
      .default([]),
    transformPatch: z
      .array(
        z
          .object({
            path: z.string().min(1),
            valueJson: z.string().max(10_000),
          })
          .strict(),
      )
      .default([]),
    transformReason: z.string().optional(),
    actionPlan: z
      .array(
        z
          .object({
            actionType: z.string().min(1),
            argsJson: z.string().max(10_000).default("{}"),
            idempotencyScope: z.enum(["event", "thread", "message", "user"]).optional(),
          })
          .strict(),
      )
      .default([]),
    preferenceUpdates: z
      .array(
        z
          .object({
            key: z.string().min(1),
            valueJson: z.string().max(4_000),
          })
          .strict(),
      )
      .default([]),
    confidence: z.number().min(0).max(1).default(0.5),
    warnings: z.array(z.string()).default([]),
    needsClarification: z.boolean().default(false),
    clarificationPrompt: z.string().optional(),
  })
  .strict();

export const ruleCompilerModelSchema = compilerOutputSchema;

export type RuleCompilerResult = {
  ok: boolean;
  candidate?: CanonicalRuleCreateInput;
  explanation: string;
  diagnostics: {
    confidence: number;
    warnings: string[];
    errors: string[];
  };
  needsClarification: boolean;
  clarificationPrompt?: string;
};

function parseJsonValue(raw: string | undefined): unknown {
  if (typeof raw !== "string") return undefined;
  const trimmed = raw.trim();
  if (!trimmed) return undefined;
  try {
    return JSON.parse(trimmed);
  } catch {
    return trimmed;
  }
}

function parseJsonObject(raw: string | undefined): Record<string, unknown> {
  const parsed = parseJsonValue(raw);
  if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
    return parsed as Record<string, unknown>;
  }
  return {};
}

function heuristicCompile(input: string): RuleCompilerResult {
  const lower = input.toLowerCase();
  if (lower.includes("working hours")) {
    return {
      ok: true,
      candidate: {
        type: "preference",
        enabled: true,
        priority: 100,
        name: "Working hours preference",
        description: "Autogenerated from natural language request.",
        scope: {
          surfaces: ["web", "slack", "discord", "telegram", "system"],
          resources: ["calendar", "preference"],
        },
        match: {
          resource: "calendar",
          operation: "create_or_reschedule",
          conditions: [],
        },
        preferencePatch: {
          updates: [],
        },
        source: {
          mode: "ai_nl",
          sourceNl: input,
          compilerVersion: "heuristic-v1",
          compilerConfidence: 0.45,
          compilerWarnings: ["Heuristic fallback parser used."],
        },
      },
      explanation:
        "I parsed this as a scheduling preference rule, but I still need exact values to activate it safely.",
      diagnostics: {
        confidence: 0.45,
        warnings: ["Heuristic fallback parser used."],
        errors: [],
      },
      needsClarification: true,
      clarificationPrompt:
        "What exact working hours/days should I enforce (for example: weekdays 9am-5pm in America/Los_Angeles)?",
    };
  }

  return {
    ok: false,
    explanation: "I could not safely compile that into a rule.",
    diagnostics: {
      confidence: 0.2,
      warnings: [],
      errors: ["Unable to infer an unambiguous canonical rule."],
    },
    needsClarification: true,
    clarificationPrompt:
      "Please describe the trigger, match condition, and expected action in one sentence.",
  };
}

function toCandidateFromModel(params: {
  input: string;
  output: z.infer<typeof compilerOutputSchema>;
}): RuleCompilerResult {
  const out = params.output;
  const candidate: CanonicalRuleCreateInput = {
    type: out.type,
    enabled: out.enabled,
    priority: out.priority,
    name: out.name,
    description: out.description,
    scope: {
      surfaces: ["web", "slack", "discord", "telegram", "system"],
      resources: [out.resource],
    },
    match: {
      resource: out.resource,
      operation: out.operation,
      conditions: out.conditions.map((condition) => ({
        field: condition.field,
        op: condition.op,
        ...(condition.valueJson !== undefined
          ? { value: parseJsonValue(condition.valueJson) }
          : {}),
      })),
    },
    ...(out.decision ? { decision: out.decision } : {}),
    ...(out.transformPatch.length > 0
      ? {
          transform: {
            patch: out.transformPatch.map((entry) => ({
              path: entry.path,
              value: parseJsonValue(entry.valueJson),
            })),
            reason: out.transformReason ?? "Applied by natural-language compiler",
          },
        }
      : {}),
    ...(out.actionPlan.length > 0
      ? {
          actionPlan: {
            actions: out.actionPlan.map((action) => ({
              actionType: action.actionType,
              args: parseJsonObject(action.argsJson),
              idempotencyScope: action.idempotencyScope,
            })),
          },
        }
      : {}),
    ...(out.preferenceUpdates.length > 0
      ? {
          preferencePatch: {
            updates: out.preferenceUpdates.map((update) => ({
              key: update.key,
              value: parseJsonValue(update.valueJson),
            })),
          },
        }
      : {}),
    source: {
      mode: "ai_nl",
      sourceNl: params.input,
      compilerVersion: "rule-compiler-v1",
      compilerConfidence: out.confidence,
      compilerWarnings: out.warnings,
    },
  };

  const parsed = canonicalRuleSchema.safeParse({
    id: "preview-rule",
    version: 1,
    ...candidate,
  });
  if (!parsed.success) {
    return {
      ok: false,
      explanation:
        "I parsed the request but the compiled rule failed strict schema validation.",
      diagnostics: {
        confidence: out.confidence,
        warnings: out.warnings,
        errors: parsed.error.issues.map((issue) => issue.message),
      },
      needsClarification: true,
      clarificationPrompt:
        out.clarificationPrompt ??
        "I need to refine that rule. Please provide a more specific condition/action.",
    };
  }

  return {
    ok: !out.needsClarification,
    candidate,
    explanation:
      out.needsClarification
        ? "I compiled a draft but it needs clarification before activation."
        : "I compiled this rule and it is ready for activation.",
    diagnostics: {
      confidence: out.confidence,
      warnings: out.warnings,
      errors: [],
    },
    needsClarification: out.needsClarification,
    clarificationPrompt: out.clarificationPrompt,
  };
}

export async function compileNaturalLanguageRule(params: {
  input: string;
  emailAccount: { id: string; email: string; userId: string };
}): Promise<RuleCompilerResult> {
  const text = params.input.trim();
  if (!text) {
    return {
      ok: false,
      explanation: "Rule text is empty.",
      diagnostics: {
        confidence: 0,
        warnings: [],
        errors: ["Empty rule input."],
      },
      needsClarification: true,
      clarificationPrompt: "Describe the rule you want to create.",
    };
  }

  try {
    const modelOptions = getModel("economy");
    const generateObject = createGenerateObject({
      emailAccount: params.emailAccount,
      label: "Natural-language rule compiler",
      modelOptions,
    });

    const { object } = await generateObject({
      model: modelOptions.model,
      schema: compilerOutputSchema,
      prompt: `Compile this user rule request into canonical rule-plane JSON.

Hard constraints:
- Be strict and deterministic.
- If information is missing, set needsClarification=true.
- Do NOT invent unknown action types.
- Keep confidence conservative.
- Encode dynamic payloads as JSON strings:
  - conditions[].valueJson
  - transformPatch[].valueJson
  - actionPlan[].argsJson
  - preferenceUpdates[].valueJson

User request:
${text}`,
    });

    return toCandidateFromModel({
      input: text,
      output: object,
    });
  } catch {
    return heuristicCompile(text);
  }
}
